version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_WS_URL=${VITE_WS_URL}
      - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
      - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM}
      - VITE_KEYCLOAK_CLIENTID=${VITE_KEYCLOAK_CLIENTID}
    ports:
      - '5500:80'
    networks:
      - app-network
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_CERTS=${KEYCLOAK_CERTS}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
